//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public int AbonementID { get; set; }
        public string Report { get; set; }
        public Nullable<int> ExpertID { get; set; }
        public int PriceOfAbonement { get; set; }
    
        public virtual AbonementsType AbonementsType { get; set; }
        public virtual Experts Experts { get; set; }
    }
}
